Update enigma2.bb
Removed 171 ENIGMA2_BRANCH ?= "${BRANCH}"
because of build error 
ERROR: ExpansionError during parsing /home/ubuntupro/openpli6.2/openpli-oe-core/meta-openpli/recipes-openpli/enigma2/enigma2.bb
Traceback (most recent call last):
bb.data_smart.ExpansionError: Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)} which triggered exception FetchError: Fetcher failure: Unable to resolve '${BRANCH}' in upstream git repository in git ls-remote output for github.com/OpenPLi/enigma2.git